<a href="https://colab.research.google.com/github/BrothaaEww/Regressions/blob/main/BGD_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
m = 200
n = 3

In [ ]:
tv = np.random.uniform(10,200,(200,1))
radio = np.random.uniform(10,100,(200,1))
newspaper = np.random.uniform(10,150,(200,1))

In [ ]:
tv[:5]

array([[ 81.63325959],
       [ 23.19430165],
       [196.66157068],
       [ 79.87608943],
       [ 29.14155646]])

In [ ]:
radio[:5]

array([[35.81239613],
       [19.29092225],
       [29.41617131],
       [34.8913969 ],
       [51.60399565]])

In [ ]:
newspaper[:5]

array([[82.83400312],
       [50.7756121 ],
       [83.2437965 ],
       [17.08881993],
       [49.53667811]])

In [ ]:
x = np.c_[tv,radio,newspaper]

In [ ]:
x.shape

(200, 3)

In [ ]:
x[:5]

array([[ 81.63325959,  35.81239613,  82.83400312],
       [ 23.19430165,  19.29092225,  50.7756121 ],
       [196.66157068,  29.41617131,  83.2437965 ],
       [ 79.87608943,  34.8913969 ,  17.08881993],
       [ 29.14155646,  51.60399565,  49.53667811]])

In [ ]:
y = 1 + 4 * tv + 2 * radio + 3 * newspaper + np.random.randn(200,1)

In [ ]:
y.shape

(200, 1)

In [ ]:
y[:5]

array([[ 647.17097003],
       [ 285.00527894],
       [1094.37699482],
       [ 441.24315105],
       [ 369.66527912]])

In [ ]:
from sklearn.preprocessing import StandardScaler

x = StandardScaler().fit_transform(x)

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin

In [ ]:
class BGDRegressor(BaseEstimator, TransformerMixin) :
  def __init__(self, eta = 0.1, n_iterations = 10000, random_state = 42) :
    self.eta = eta
    self.n_iterations = n_iterations
    self.random_state = random_state
    np.random.seed(self.random_state)

  def fit(self,x,y):
    m, n = x.shape
    x_b = np.c_[np.ones((len(x),1)),x]
    self.theta = np.random.randn(n + 1, 1)
    for iteration in range(self.n_iterations):
      gradients = 2 / m * x_b.T @ (x_b @ self.theta - y)
      self.theta = self.theta - self.eta * gradients
    return self

  def predict(self,x):
    x_b = np.c_[np.ones((len(x),1)),x]
    y_predicts = x_b @ self.theta
    return y_predicts

In [ ]:
lin_reg = BGDRegressor()

In [ ]:
lin_reg.fit(x,y)

BGDRegressor()

In [ ]:
lin_reg.theta

array([[763.75736085],
       [214.92047833],
       [ 47.39568896],
       [125.78365024]])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg_1 = LinearRegression()

In [ ]:
lin_reg_1.fit(x,y)

LinearRegression()

In [ ]:
print(lin_reg_1.intercept_)
print(lin_reg_1.coef_)

[763.75736085]
[[214.92047833  47.39568896 125.78365024]]


In [ ]:
y[:5]

array([[ 647.17097003],
       [ 285.00527894],
       [1094.37699482],
       [ 441.24315105],
       [ 369.66527912]])

In [ ]:
print(lin_reg.predict(x[:5]))

[[ 647.62156981]
 [ 284.57776561]
 [1096.08699162]
 [ 441.44287357]
 [ 369.40109257]]


In [ ]:
print(lin_reg_1.predict(x[:5]))

[[ 647.62156981]
 [ 284.57776561]
 [1096.08699162]
 [ 441.44287357]
 [ 369.40109257]]
