<a href="https://colab.research.google.com/github/BrothaaEww/Regressions/blob/main/my_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
m = 200
n = 3

In [ ]:
tv = np.random.uniform(10,200,(200,1))
radio = np.random.uniform(10,100,(200,1))
newspaper = np.random.uniform(10,150,(200,1))

In [ ]:
tv[:5]

array([[ 37.35182501],
       [101.60365463],
       [118.54275618],
       [102.42034604],
       [110.13250795]])

In [ ]:
radio[:5]

array([[87.51393792],
       [64.63006526],
       [98.45374667],
       [93.50152101],
       [78.94448916]])

In [ ]:
newspaper[:5]

array([[142.7004986 ],
       [ 29.68699528],
       [127.83670563],
       [ 15.00065542],
       [ 11.13416731]])

In [ ]:
x = np.c_[tv,radio,newspaper]

In [ ]:
x.shape

(200, 3)

In [ ]:
x[:5]

array([[ 37.35182501,  87.51393792, 142.7004986 ],
       [101.60365463,  64.63006526,  29.68699528],
       [118.54275618,  98.45374667, 127.83670563],
       [102.42034604,  93.50152101,  15.00065542],
       [110.13250795,  78.94448916,  11.13416731]])

In [ ]:
y = 1 + 4 * tv + 2 * radio + 3 * newspaper + np.random.randn(200,1)

In [ ]:
y.shape

(200, 1)

In [ ]:
y[:5]

array([[ 754.37171205],
       [ 626.42902659],
       [1056.8353424 ],
       [ 639.72854619],
       [ 631.73806276]])

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin

In [ ]:
class MyLinearRegression(BaseEstimator, TransformerMixin) :
  def __init__(self, **kwargs) :
    pass

  def fit(self,x,y):
    x_b = np.c_[np.ones((len(x),1)),x]
    self.theta_best = np.linalg.inv(x_b.T @ x_b) @ x_b.T @ y
    self.intercept_ = self.theta_best[0]
    self.coef_ = self.theta_best[1:]
    return self

  def predict(self,x):
    x_b = np.c_[np.ones((len(x),1)),x]
    y_predicts = x_b @ self.theta_best
    return y_predicts

In [ ]:
lin_reg=MyLinearRegression()

In [ ]:
lin_reg.fit(x,y)

MyLinearRegression()

In [ ]:
lin_reg.theta_best

array([[0.94888782],
       [3.99984797],
       [2.00260369],
       [2.99935678]])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg_1 = LinearRegression()

In [ ]:
lin_reg_1.fit(x,y)

LinearRegression()

In [ ]:
print(lin_reg_1.intercept_)
print(lin_reg_1.coef_)

[0.94888782]
[[3.99984797 2.00260369 2.99935678]]


In [ ]:
y[:5]

array([[361.01783962],
       [862.60676132],
       [570.48766388],
       [556.6990876 ],
       [492.06609924]])

In [ ]:
print(lin_reg.predict(x[:5]))

[[360.89385612]
 [861.35001833]
 [570.31763136]
 [555.70031295]
 [490.65580556]]


In [ ]:
print(lin_reg_1.predict(x[:5]))

[[360.89385612]
 [861.35001833]
 [570.31763136]
 [555.70031295]
 [490.65580556]]
