<a href="https://colab.research.google.com/github/BrothaaEww/Regressions/blob/main/SGD_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
m = 200
n = 3

In [ ]:
tv = np.random.uniform(10,200,(200,1))
radio = np.random.uniform(10,100,(200,1))
newspaper = np.random.uniform(10,150,(200,1))

In [ ]:
tv[:5]

array([[ 81.63325959],
       [ 23.19430165],
       [196.66157068],
       [ 79.87608943],
       [ 29.14155646]])

In [ ]:
radio[:5]

array([[35.81239613],
       [19.29092225],
       [29.41617131],
       [34.8913969 ],
       [51.60399565]])

In [ ]:
newspaper[:5]

array([[82.83400312],
       [50.7756121 ],
       [83.2437965 ],
       [17.08881993],
       [49.53667811]])

In [ ]:
x = np.c_[tv,radio,newspaper]

In [ ]:
x.shape

(200, 3)

In [ ]:
x[:5]

array([[ 81.63325959,  35.81239613,  82.83400312],
       [ 23.19430165,  19.29092225,  50.7756121 ],
       [196.66157068,  29.41617131,  83.2437965 ],
       [ 79.87608943,  34.8913969 ,  17.08881993],
       [ 29.14155646,  51.60399565,  49.53667811]])

In [ ]:
y = 1 + 4 * tv + 2 * radio + 3 * newspaper + np.random.randn(200,1)

In [ ]:
y.shape

(200, 1)

In [ ]:
y[:5]

array([[ 880.47935809],
       [ 738.9243058 ],
       [1145.95164832],
       [ 968.44094602],
       [ 699.97145411]])

In [ ]:
from sklearn.preprocessing import StandardScaler

x = StandardScaler().fit_transform(x)

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin

In [ ]:
class SGDRegressor(BaseEstimator, TransformerMixin) :
  def __init__(self, eta = 0.1, n_epochs = 50) :
    self.eta = eta
    self.n_epochs = n_epochs
    self.t0 = 5
    self.t1 = 50

  def fit(self,x,y):
    m, n = x.shape
    x_b = np.c_[np.ones((len(x),1)),x]
    self.theta = np.random.randn(n + 1, 1)
    for epoch in range(self.n_epochs):
      for i in range(m):
        random_index = np.random.randint(m)
        xi = x_b[random_index: random_index + 1]
        yi = y[random_index: random_index + 1]
        gradients = 2 * xi.T @ (xi @ self.theta - yi)
        self.eta = self.learning_schedule(epoch * m + i)
        self.theta = self.theta - self.eta * gradients
    return self

  def predict(self,x):
    x_b = np.c_[np.ones((len(x),1)),x]
    y_predicts = x_b @ self.theta
    return y_predicts

  def learning_schedule(self, t):
    return self.t0 / (t + self.t1)

In [ ]:
lin_reg = SGDRegressor()

In [ ]:
lin_reg.fit(x,y)

SGDRegressor(eta=0.0004975619464623346)

In [ ]:
lin_reg.theta

array([[769.49729958],
       [221.73628533],
       [ 51.19547712],
       [126.85909053]])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg_1 = LinearRegression()

In [ ]:
lin_reg_1.fit(x,y)

LinearRegression()

In [ ]:
print(lin_reg_1.intercept_)
print(lin_reg_1.coef_)

[769.49860315]
[[221.72738238  51.17133309 126.8392679 ]]


In [ ]:
y[:5]

array([[ 880.47935809],
       [ 738.9243058 ],
       [1145.95164832],
       [ 968.44094602],
       [ 699.97145411]])

In [ ]:
print(lin_reg.predict(x[:5]))

[[ 879.79583187]
 [ 739.25885782]
 [1146.70120599]
 [ 967.80422433]
 [ 700.4892432 ]]


In [ ]:
print(lin_reg_1.predict(x[:5]))

[[ 879.80104825]
 [ 739.26322425]
 [1146.69529612]
 [ 967.81361013]
 [ 700.48118198]]
